version: "3.9"

services:
  crm_server:
    image: adva1/crm_server:latest
    container_name: crm_server
    restart: unless-stopped
    env_file:
      - ./server/.env
    expose:
      - "3000"

  crm_client:
    image: adva1/crm_client:latest
    container_name: crm_client
    restart: unless-stopped
    depends_on:
      - crm_server
    expose:
      - "80"