name: CI/CD - Test, Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  # --------------------
  # CI - Tests
  # --------------------
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: server
        run: npm install

      - name: Run tests
        working-directory: server
        run: npm test

  # --------------------
  # Build & Push Images
  # --------------------
  build:
    runs-on: ubuntu-latest
    needs: test   #  CD לא רץ אם CI נכשל

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # -------- SERVER --------
      - name: Build & Push Server Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/crm-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/crm-server:${{ github.sha }}

      # -------- CLIENT --------
      - name: Build & Push Client Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/crm-client:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/crm-client:${{ github.sha }}

  # --------------------
  # Deploy
  # --------------------
deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy docker-compose and nginx
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: docker-compose.yml,client/nginx.conf
        target: ~/crm

    - name: Deploy on VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          cd ~/crm

          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

          docker compose pull
          docker compose up -d --force-recreate

          echo "Deployment completed successfully"